from typing import Set

MIN_FILE_SIZE = 100 * 1024  # 100 KB
DEFAULT_TOP_N = 10

# Use strings for faster lookups (avoiding Path object creation overhead during checks)
SKIP_DIRS: Set[str] = {
    # Linux
    "/dev",
    "/proc",
    "/sys",
    "/run",
    "/var/run",
    "/snap",
    "/boot",
    "/lost+found",
    # macOS
    "/System",
    "/Library",
    "/private/var",
    "/.Spotlight-V100",
    "/.DocumentRevisions-V100",
    "/.fseventsd",
}

# SKIP_DIRS contains only root-level system paths (e.g., /dev, /proc, /System).
# We only check against SKIP_DIRS when level <= DEEPEST_SKIP_LEVEL as an optimization:
# deeper scans (e.g., /home/user/project) can never encounter these paths.
DEEPEST_SKIP_LEVEL = 3

CATEGORIES = {
    "Pictures": {
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".bmp",
        ".tiff",
        ".svg",
        ".webp",
        ".heic",
        ".ico",
        ".raw",
        ".avif",
    },
    "Documents": {
        ".doc",
        ".docx",
        ".pdf",
        ".txt",
        ".xls",
        ".xlsx",
        ".ppt",
        ".pptx",
        ".odt",
        ".rtf",
        ".md",
        ".epub",
        ".mobi",
        ".pages",
        ".numbers",
        ".key",
    },
    "Music": {".mp3", ".wav", ".aac", ".flac", ".m4a", ".ogg", ".wma", ".opus", ".aiff"},
    "Videos": {
        ".mp4",
        ".avi",
        ".mkv",
        ".mov",
        ".wmv",
        ".flv",
        ".webm",
        ".m4v",
        ".mts",
        ".vob",
        ".3gp",
    },
    "Code": {
        ".py",
        ".js",
        ".html",
        ".css",
        ".java",
        ".cpp",
        ".c",
        ".rb",
        ".go",
        ".rs",
        ".ts",
        ".jsx",
        ".tsx",
        ".ipynb",
        ".sh",
        ".bash",
        ".zsh",
        ".ps1",
        ".swift",
        ".kt",
        ".scala",
        ".php",
        ".vue",
        ".svelte",
        ".h",
        ".hpp",
    },
    "Archives": {".tar", ".gz", ".zip", ".rar", ".7z", ".bz2", ".xz", ".tgz", ".lz", ".zst"},
    "Disk Images": {".iso", ".dmg", ".img", ".vdi", ".vmdk", ".qcow2", ".vhd", ".vhdx"},
    "Config": {".yml", ".yaml", ".json", ".toml", ".xml", ".ini", ".env", ".conf"},
    "ML Models": {
        ".pt",
        ".pth",
        ".onnx",
        ".keras",
        ".safetensors",
        ".tflite",
        ".gguf",
        ".pkl",
        ".pb",
        ".ckpt",
    },
    "Databases": {
        ".db",
        ".sqlite",
        ".sqlite3",
        ".h5",
        ".hdf5",
        ".parquet",
        ".mdb",
        ".accdb",
        ".dbf",
        ".csv",
        ".tsv",
        ".avro",
        ".duckdb",
    },
    "3D Models": {".obj", ".fbx", ".stl", ".blend", ".gltf", ".glb"},
    "Executables": {".exe", ".dll", ".so", ".dylib"},
    "Fonts": {".ttf", ".otf", ".woff", ".woff2", ".eot"},
}

# Special directories to treat as atomic units
SPECIAL_DIRS = {
    "Virtual Environments": {
        ".venv",
        "venv",
        "env",
        "virtualenv",
        ".virtualenv",
        "conda",
        ".conda",
        "miniconda3",
        "anaconda3",
    },
    "Node Modules": {"node_modules"},
    "Build Artifacts": {
        "target",
        "build",
        "dist",
        ".gradle",
        ".cargo",
        "out",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".turbo",
        ".bazel",
        "bazel-bin",
        "bazel-out",
    },
    "Package Caches": {
        ".npm",
        ".yarn",
        ".m2",
        ".pip",
        "__pycache__",
        ".cache",
        ".pnpm",
        ".uv",
        "vendor",
        ".bundle",
        ".bun",
        ".deno",
    },
    "IDE Config": {".idea", ".vscode", ".vs", ".eclipse", ".fleet"},
    "Git Repos": {".git"},
    "Temp Files": {"tmp", "temp", ".tmp"},
    "ML Artifacts": {"models", "weights", "checkpoints", "pretrained"},
}

# Pre-compute lookups for O(1) access
EXTENSION_MAP = {ext: cat for cat, exts in CATEGORIES.items() for ext in exts}
SPECIAL_DIR_MAP = {name: cat for cat, names in SPECIAL_DIRS.items() for name in names}
PROGRESS_UPDATE_THRESHOLD = 10 * 1024 * 1024  # 10 MB
